---
- name: Get Facts from machines
  hosts: "{{ awx_group }}"
  gather_facts: no
  vars:
    ansible_host_key_checking: False
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Get ansible facts
      debug:
          var: ansible_facts
    
    - name: Teste Conexão
      shell: echo "teste"

